{"name": "test_add_contact_in_group", "status": "broken", "statusDetails": {"message": "AttributeError: 'Contact' object has no attribute 'identifier'", "trace": "app = <fixture.application.Application object at 0x0000019DC86F81D0>\norm = <fixture.orm.ORMFixture object at 0x0000019DC85B66D8>, check_ui = False\n\n    def test_add_contact_in_group(app, orm, check_ui):\n        with allure.step('Given a non-empty contact list'):\n            if app.contact.count() == 0:\n               app.contact.create(Contact(firstname=\"A8888l6\", secondname=\"Rs88\", lastname=\"81\", homephone=\"33333\", mobilephone=\"2222\",\n                          workphone=\"1111\", secondaryphone=\"555555\", email=\"aeg5@mail.ru\", email2=\"123592@mail.ru\",\n                          email3=\"sasha1992@mail.ru\", address=\"LasVegas\"))\n            contacts = orm.get_contact_list()\n            with allure.step('Given a non-empty group list'):\n                if app.group.count() == 0:\n                    app.group.create(Group(name='Test'))\n                groups = orm.get_group_list()\n            if orm.all_contacts_in_all_groups(groups):\n                app.group.create(Group(name='Test'))\n        with allure.step('Given a random contact from the list'):\n            edit_contact = random.choice(contacts)\n        with allure.step('Given a random group from the list'):\n            add_group_to_contact = random.choice(groups)\n        with allure.step('When I add contact %s in group %s from the list' % (edit_contact, add_group_to_contact)):\n>           app.contact.add_contact_in_group_by_id(edit_contact.identifier, add_group_to_contact.identifier)\nE           AttributeError: 'Contact' object has no attribute 'identifier'\n\ntest\\test_add_contact_in_group.py:25: AttributeError"}, "steps": [{"name": "Given a non-empty contact list", "status": "passed", "steps": [{"name": "Given a non-empty group list", "status": "passed", "start": 1613232652795, "stop": 1613232653021}], "start": 1613232652451, "stop": 1613232653030}, {"name": "Given a random contact from the list", "status": "passed", "start": 1613232653030, "stop": 1613232653030}, {"name": "Given a random group from the list", "status": "passed", "start": 1613232653030, "stop": 1613232653030}, {"name": "When I add contact 4:firstnameg0X)QOj&:lastnamesyn;Qotk-U :None:None:None in group 3:name6B#Bc i:headerrldZ% $T)a4A:footeraG%zy# from the list", "status": "broken", "statusDetails": {"message": "AttributeError: 'Contact' object has no attribute 'identifier'\n", "trace": "  File \"C:\\Users\\1395371\\DD\\test\\test_add_contact_in_group.py\", line 25, in test_add_contact_in_group\n    app.contact.add_contact_in_group_by_id(edit_contact.identifier, add_group_to_contact.identifier)\n"}, "start": 1613232653030, "stop": 1613232653030}], "start": 1613232652450, "stop": 1613232653030, "uuid": "597e85b3-3595-4dcf-8c9b-6d193b8e661f", "historyId": "573a25813011d82427453b445fb1edab", "testCaseId": "35c38a005f31ebde08b846fd9c0b0e4b", "fullName": "test.test_add_contact_in_group#test_add_contact_in_group", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_add_contact_in_group"}, {"name": "host", "value": "LAPTOP-F7DMISNI"}, {"name": "thread", "value": "9144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_add_contact_in_group"}]}